[env:bluepill_f103c6]
platform = ststm32
board = bluepill_f103c6
debug_speed = 1000

# 🔥 唯一修改：严格匹配你的真实文件名（一字不差）
board_build.ldscript = STM32F103XX_FLASH.ld

build_flags = 
    -Isrc
    -Iinclude
    -IDrivers/STM32F1xx_HAL_Driver/Inc
    -IDrivers/CMSIS/Device/ST/STM32F1xx/Include
    -IDrivers/CMSIS/Include
    -IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc
    -IMiddlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc
    -IUSB_DEVICE/App
    -IUSB_DEVICE/Target
    -DUSE_HAL_DRIVER
    -DSTM32F103x6

build_src_filter = 
    +<*.c>
    +<*.S>
    +<../Core/Src/*.c>
    +<../Drivers/STM32F1xx_HAL_Driver/Src/*.c>
    -<../Drivers/STM32F1xx_HAL_Driver/Src/*_template.c>
    +<../Middlewares/ST/STM32_USB_Device_Library/Core/Src/*.c>
    -<../Middlewares/ST/STM32_USB_Device_Library/Core/Src/*_template.c>
    +<../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src/*.c>
    -<../Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src/*_template.c>
    +<../USB_DEVICE/App/*.c>
    +<../USB_DEVICE/Target/*.c>

upload_protocol = stlink
debug_tool = stlink
