[env:bluepill_f103c6]
platform = ststm32
board = bluepill_f103c6
framework = stm32cube
debug_speed = 1000
upload_protocol = stlink
debug_tool = stlink

lib_deps = 
    https://github.com/hathach/tinyusb.git

build_flags = 
    -D CFG_TUSB_MCU=OPT_MCU_STM32F1
    -D CFG_TUSB_OS=OPT_OS_NONE
    -Isrc
    -Iinclude
    -DUSE_HAL_DRIVER
    -DSTM32F103x6
    -O2

build_src_filter = 
    +<*.c>
    +<*.S>
